name: Convert Images and Push to Deploy

on:
  push:
    branches: [main]

jobs:
  convert-images:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install sharp
        run: bun install sharp
      
      - name: Get last commit message from main
        id: last_commit
        run: |
          last_commit_message=$(git log -1 --pretty=%B)
          echo "last_commit_message=$last_commit_message" >> "$GITHUB_OUTPUT"

      - name: Detect changed and deleted PNG files
        id: detect
        run: |
          mkdir -p tmp
          # 1. Detect added or modified PNG files
          git diff --name-status HEAD^ HEAD | grep -E '^A|^M' | awk '{ print $2 }' | grep '^public/.*\.png$' > tmp/changed_files.txt || true
          # 2. Detect deleted PNG files
          git diff --name-status HEAD^ HEAD | grep '^D' | awk '{ print $2 }' | grep '^public/.*\.png$' > tmp/deleted_files.txt || true
          # 3. Output
          echo "changed=$(cat tmp/changed_files.txt | tr '\n' ' ')" >> "$GITHUB_OUTPUT"
          echo "deleted=$(cat tmp/deleted_files.txt | tr '\n' ' ')" >> "$GITHUB_OUTPUT"
          rm -rf tmp

      - name: Checkout deploy branch as worktree
        run: |
          git fetch origin deploy
          git worktree add -b deploy-local deploy-temp origin/deploy
      
      - name: Prepare merge commit to deploy branch
        run: |
          cd deploy-temp
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git merge --no-commit --no-ff origin/main
          cd ..

      - name: Copy existing optimized images and other files from deploy
        run: |
          mkdir -p optimized/public
          [ -d deploy-temp/public ] && rsync -a --include='*/' --include='*.webp' --include='*.avif' --exclude='*' deploy-temp/public/ optimized/public/ || true
      
      - name: Copy image files excluded from optimization
        run: |
          mkdir -p optimized/public/AppImages
          mkdir -p optimized/public/fonts
          cp -r public/AppImages/* optimized/public/AppImages/
          cp -r public/fonts/* optimized/public/fonts/
          cp public/favicon-16x16.png optimized/public/favicon-16x16.png
          cp public/favicon-32x32.png optimized/public/favicon-32x32.png
          cp public/favicon.ico optimized/public/favicon.ico
      
      - name: Copy other source files
        run: |
          rsync -a \
          --exclude='deploy-temp' \
          --exclude='optimized' \
          --exclude='.git' \
          --exclude='public' \
          --exclude='node_modules' \
          ./ optimized/

      - name: Convert changed PNGs to WebP and AVIF
        if: steps.detect.outputs.changed != ''
        run: |
          mkdir -p public
          for file in ${{ steps.detect.outputs.changed }}; do
            filename="${file#public/}"
            mkdir -p "optimized/public/$(dirname "$filename")"
            bun -e "const sharp = require('sharp'); sharp('$file').webp({ quality: 80 }).toFile('optimized/public/${filename%.png}.webp')"
            # bun -e "const sharp = require('sharp'); sharp('$file').avif({ quality: 50 }).toFile('optimized/public/${filename%.png}.avif')"
          done

      - name: Remove sharp
        run: bun uninstall sharp

      - name: Remove deleted PNG's converted versions
        if: steps.detect.outputs.deleted != ''
        run: |
          for file in ${{ steps.detect.outputs.deleted }}; do
            filename="${file#public/}"
            rm -f "optimized/public/${filename%.png}.webp"
            # rm -f "optimized/public/${filename%.png}.avif"
          done

      - name: Prepare deploy directory
        run: |
          mkdir -p deploy-temp/public
          rm -rf deploy-temp/*
          rm -rf deploy-temp/.github
          cp -r optimized/* deploy-temp/
          cp -r optimized/.github deploy-temp/.github

      - name: Replace .png to .webp for load optimized images
        run: |
          cd optimized
          find . \( -wholename './vite.config.ts' -o -wholename './tailwind.config.ts' -o -wholename './src/*.ts' -o -wholename './src/*.tsx' \) > files_to_check.txt
          while IFS= read -r file; do
            awk '
            /\/AppImages\// || /https:/ || /apple-touch-icon/ {
              print; next
            }
            {
              gsub(/\.png"/, ".webp\"");
              gsub(/\.png'\''/, ".webp'\''");
              gsub(/\.png`/, ".webp`");
              print
            }
            ' "$file" > "../deploy-temp/$file"
          done < files_to_check.txt
          rm files_to_check.txt
          cd ..

      - name: Commit and push to deploy branch
        run: |
          cd deploy-temp
          git add *
          git commit -m "${{ steps.last_commit.outputs.last_commit_message }}" || echo "Nothing to commit"
          git push origin HEAD:deploy
          cd ..

      - name: Cleanup
        run: |
          git worktree remove deploy-temp --force
          rm -rf deploy-temp
