name: Convert Images and Push to Deploy

on:
  push:
    branches: [main]

jobs:
  convert-images:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install sharp
        run: bun install sharp

      - name: Detect changed and deleted PNG files
        id: detect
        run: |
          mkdir -p tmp
          # 1. Detect added or modified PNG files
          git diff --name-status HEAD^ HEAD | grep -E '^A|^M' | awk '{ print $2 }' | grep '^public/.*\.png$' > tmp/changed_files.txt || true
          # 2. Detect deleted PNG files
          git diff --name-status HEAD^ HEAD | grep '^D' | awk '{ print $2 }' | grep '^public/.*\.png$' > tmp/deleted_files.txt || true
          # 3. Output
          echo "changed=$(cat tmp/changed_files.txt | tr '\n' ' ')" >> "$GITHUB_OUTPUT"
          echo "deleted=$(cat tmp/deleted_files.txt | tr '\n' ' ')" >> "$GITHUB_OUTPUT"


      - name: Checkout deploy branch
        uses: actions/checkout@v4
        with:
          ref: deploy
          path: deploy-temp

      - name: Copy all files from main branch
        run: |
          rsync -a --delete ./ ./deploy-temp/

      - name: Convert changed PNGs to WebP and AVIF
        if: steps.detect.outputs.changed != ''
        run: |
          mkdir -p public
          while IFS= read -r file; do
            [ -z "$file" ] && continue
            filename="${file#public/}"
            mkdir -p "optimized/public/$(dirname "$filename")"
            node -e "const sharp = require('sharp'); sharp('$file').toFile('optimized/public/${filename%.png}.webp')"
            # node -e "const sharp = require('sharp'); sharp('$file').toFile('optimized/public/${filename%.png}.avif')"
          done < changed_pngs.txt

      - name: Remove deleted PNG's converted versions
        if: steps.detect.outputs.deleted != ''
        run: |
          for file in ${{ steps.detect.outputs.deleted }}; do
            rm -f "${file%.png}.webp" # "${file%.png}.avif"
          done

      - name: Commit and push to deploy branch
        run: |
          cd deploy-temp
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add public/
          git commit -m "Convert updated PNG images [bot]" || echo "Nothing to commit"
          git push origin HEAD:deploy --force

      - name: Cleanup worktree
        run: |
          rm -rf deploy-temp
